version: '3'

services:
  app:
    build: .
    container_name: ekin-image-api
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./db.sqlite:/app/db.sqlite
    restart: unless-stopped 